import { useEffect, useState } from "react";
import { request, type Model } from "./api";
import "./inspection.scss";
type Call = {call_id:string;created_at_ms:number;display_name:string;model_id:string;status:string;http_status:number|null;duration_ms:number|null;ttfb_ms:number|null;ttfr_ms:number|null;ttft_ms:number|null;input_tokens:number|null;output_tokens:number|null;cache_read_tokens:number|null;cache_write_tokens:number|null;request_id:string|null;conversation_id:string;parent_request_id:string|null;parent_tool_call_id:string|null;request_url:string;method:string;route:string;error_message:string|null;error_kind:string|null};
type Page = {items:Call[];total:number;page:number;limit:number};
type Diagnostic = {id:number;created_at_ms:number;request_id:string|null;conversation_id:string|null;parent_request_id:string|null;parent_tool_call_id:string|null;method:string;path:string;route:string;stage:string;http_status:number;duration_ms:number};
const n = (v:number|null) => v === null ? "—" : v.toLocaleString();
export function Calls({models}:{models:Model[]}) {
 const [page,setPage]=useState(1),[model,setModel]=useState(""),[status,setStatus]=useState(""),[start,setStart]=useState(""),[end,setEnd]=useState(""),[conversation,setConversation]=useState("");
 const [data,setData]=useState<Page|null>(null),[selected,setSelected]=useState<Call|null>(null),[error,setError]=useState(""),[refresh,setRefresh]=useState(0),[busy,setBusy]=useState(false);
 const [diagnostics,setDiagnostics]=useState<Diagnostic[]>([]),[requestId,setRequestId]=useState(""),[before,setBefore]=useState<number|null>(null);
 useEffect(()=>{let active=true;setBusy(true);setError("");const q=new URLSearchParams({page:String(page),limit:"25"});if(model)q.set("model_hash",model);if(status)q.set("status",status);if(start)q.set("start_ms",String(new Date(start).getTime()));if(end)q.set("end_ms",String(new Date(end).getTime()));if(conversation)q.set("conversation_id",conversation);
 void request<Page>(`llm-calls?${q}`).then(v=>{if(active)setData(v);}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setBusy(false);});return()=>{active=false;};},[page,model,status,start,end,conversation,refresh]);
 useEffect(()=>{let active=true;const q=new URLSearchParams();if(requestId)q.set("request_id",requestId);if(before)q.set("before",String(before));void request<Diagnostic[]>(`route-diagnostics?${q}`).then(v=>{if(active)setDiagnostics(v);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[requestId,before,refresh]);
 const filter=(f:()=>void)=>{f();setPage(1);};
 return <><section className="card inspection"><div className="section-heading"><div><h2>调用记录</h2><p className="hint">仅元数据与脱敏错误；时间按本机时区，结束时间不包含在区间内。</p></div><button disabled={busy} onClick={()=>setRefresh(v=>v+1)}>刷新</button></div>
 <div className="inspection-filters"><label>起始时间<input type="datetime-local" value={start} onChange={e=>filter(()=>setStart(e.target.value))}/></label><label>结束时间<input type="datetime-local" value={end} onChange={e=>filter(()=>setEnd(e.target.value))}/></label><label>模型<select value={model} onChange={e=>filter(()=>setModel(e.target.value))}><option value="">全部模型</option>{models.map(m=><option key={m.model_hash} value={m.model_hash}>{m.display_name}</option>)}</select></label><label>结果<select value={status} onChange={e=>filter(()=>setStatus(e.target.value))}><option value="">全部结果</option><option value="success">成功</option><option value="failed">失败／取消</option><option value="running">进行中</option></select></label><label>对话 ID<input value={conversation} onChange={e=>filter(()=>setConversation(e.target.value))}/></label></div>
 {error&&<div className="alert error">{error}</div>}<div className="table-scroll"><table><thead><tr><th>本地时间</th><th>模型</th><th>结果 / HTTP</th><th>耗时</th><th>输入 / 输出</th><th>详情</th></tr></thead><tbody>{data?.items.map(c=><tr key={c.call_id}><td>{new Date(c.created_at_ms).toLocaleString()}</td><td>{c.display_name}</td><td>{c.status} / {c.http_status??"—"}</td><td>{n(c.duration_ms)} ms</td><td>{n(c.input_tokens)} / {n(c.output_tokens)}</td><td><button onClick={()=>{setSelected(c);setRequestId(c.request_id??"");setBefore(null);}}>查看</button></td></tr>)}</tbody></table></div>{!busy&&!data?.items.length&&<p className="hint">当前范围没有调用记录。</p>}<div className="row-actions"><button disabled={page===1||busy} onClick={()=>setPage(p=>p-1)}>上一页</button><span>第 {page} 页 · 共 {data?.total??0} 条</span><button disabled={busy||page*25>=(data?.total??0)} onClick={()=>setPage(p=>p+1)}>下一页</button></div></section>
 {selected&&<section className="card inspection"><div className="section-heading"><h2>请求详情</h2><button onClick={()=>setSelected(null)}>收起</button></div><dl><dt>关联 ID</dt><dd>{selected.call_id}</dd><dt>Cursor 请求 / 对话</dt><dd>{selected.request_id??"未记录"}<br/>{selected.conversation_id}</dd><dt>父请求 / Task</dt><dd>{selected.parent_request_id??"客户端未提供"}<br/>{selected.parent_tool_call_id??"未记录"}</dd><dt>路由</dt><dd>{selected.route} · {selected.method} {selected.request_url}</dd><dt>首响应</dt><dd>响应头 {n(selected.ttfb_ms)} ms · 首有效事件 {n(selected.ttfr_ms)} ms · 首文字 {n(selected.ttft_ms)} ms</dd><dt>缓存读取 / 写入</dt><dd>{n(selected.cache_read_tokens)} / {n(selected.cache_write_tokens)}</dd><dt>错误</dt><dd>{selected.error_kind??"—"} {selected.error_message??""}</dd></dl>{selected.parent_request_id&&<button onClick={()=>{setRequestId(selected.parent_request_id!);setBefore(null);}}>定位父请求及子请求</button>}</section>}
 <section className="card inspection"><h2>Cursor 路由诊断</h2><p className="hint">最近 10,000 条建链及失败事件；HTTP 200 只表示建链成功，不代表模型任务完成。旧版本未记录的关系不猜测补齐。</p><label>请求关联 ID<input value={requestId} onChange={e=>{setRequestId(e.target.value);setBefore(null);}} placeholder="留空查看全部路由"/></label><div className="table-scroll"><table><thead><tr><th>本地时间</th><th>请求</th><th>来源 / 阶段</th><th>状态 / 耗时</th><th>关联</th></tr></thead><tbody>{diagnostics.map(d=><tr key={d.id}><td>{new Date(d.created_at_ms).toLocaleString()}</td><td>{d.method} {d.path}</td><td>{d.route}<br/>{d.stage}</td><td>{d.http_status} / {d.duration_ms} ms</td><td><button title={d.request_id??""} onClick={()=>{setRequestId(d.request_id??"");setBefore(null);}}>{d.request_id?.slice(0,12)??"未解码"}</button><small>父 {d.parent_request_id??"未提供"}<br/>Task {d.parent_tool_call_id??"未提供"}</small></td></tr>)}</tbody></table></div>{!diagnostics.length&&<p className="hint">没有匹配诊断。</p>}<div className="row-actions"><button disabled={!before} onClick={()=>setBefore(null)}>最新</button><button disabled={diagnostics.length<100} onClick={()=>setBefore(diagnostics[diagnostics.length-1].id)}>更早记录</button></div></section></>;
}
