import { useEffect, useState, type FormEvent } from "react";
import { request } from "./api";
type Network = {ports:{proxy_port:number;service_port:number};outbound:{mode:"default"|"direct"|"custom";address:string;auth_enabled:boolean;username:string;has_password:boolean};actual_service_port:number|null;actual_proxy_port:number|null};
export function NetworkSettings({locked}:{locked:boolean}) {
 const [data,setData]=useState<Network|null>(null),[password,setPassword]=useState(""),[error,setError]=useState(""),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false);
 useEffect(()=>{void request<Network>("network").then(setData).catch(e=>setError(e.message));},[]);
 async function save(e:FormEvent,kind:"ports"|"proxy") {e.preventDefault();if(!data)return;setBusy(true);setError("");setNotice("");try{setData(await request<Network>(`network/${kind}`,"PUT",kind==="ports"?data.ports:{...data.outbound,has_password:undefined,password:password||undefined}));setPassword("");setNotice(kind==="ports"?"端口已保存：管理端口在重启应用后生效；接管端口在下次开启接管时生效。":"出站代理已保存，新发起的应用 HTTP 请求使用新设置。");}catch(e){setError(e instanceof Error?e.message:"保存失败");}finally{setBusy(false);}}
 return <>{error&&<div className="alert error">{error}</div>}{notice&&<div className="alert">{notice}</div>}{data&&<><section className="card"><h2>应用出站代理</h2><p className="hint">用于控制器转发至 Sub2API 和 Cursor API 的 HTTP 请求；不更改 Windows 系统代理。Cursor 其他直通流量仍沿用自身网络方式。</p><form onSubmit={e=>void save(e,"proxy")}><div className="fields"><label>模式<select disabled={locked||busy} value={data.outbound.mode} onChange={e=>setData({...data,outbound:{...data.outbound,mode:e.target.value as Network["outbound"]["mode"]}})}><option value="default">跟随进程环境代理</option><option value="direct">直接连接</option><option value="custom">自定义代理</option></select></label>{data.outbound.mode==="custom"&&<label>代理地址<input disabled={locked||busy} required value={data.outbound.address} placeholder="http://127.0.0.1:7890" onChange={e=>setData({...data,outbound:{...data.outbound,address:e.target.value}})}/></label>}</div>{data.outbound.mode==="custom"&&<><label><input type="checkbox" disabled={locked||busy} checked={data.outbound.auth_enabled} onChange={e=>setData({...data,outbound:{...data.outbound,auth_enabled:e.target.checked}})}/>需要代理认证</label>{data.outbound.auth_enabled&&<div className="fields"><label>用户名<input disabled={locked||busy} value={data.outbound.username} onChange={e=>setData({...data,outbound:{...data.outbound,username:e.target.value}})}/></label><label>密码<input type="password" autoComplete="off" disabled={locked||busy} placeholder={data.outbound.has_password?"已用 DPAPI 保存；留空保留":"输入代理密码"} value={password} onChange={e=>setPassword(e.target.value)}/></label></div>}</>}<div className="form-footer"><span>接管期间配置锁定；代理失败不会自动改为直连。</span><button disabled={locked||busy}>保存出站设置</button></div></form><button disabled={busy} onClick={()=>{setBusy(true);setError("");void request<{status:number;duration_ms:number}>("network/test","POST").then(r=>setNotice(`已保存配置的连接测试：${r.duration_ms} ms，Cursor 公共入口 HTTP ${r.status}；未携带账号凭据，不代表模型权限通过。`)).catch(e=>setError(e.message)).finally(()=>setBusy(false));}}>测试已保存代理（不调用模型）</button></section>
 <section className="card"><h2>本地监听端口</h2><p className="hint">仅监听 127.0.0.1，管理 token、Host、Origin 校验继续生效。0 表示自动分配；指定端口启动时被占用将报错。</p><form onSubmit={e=>void save(e,"ports")}><div className="fields"><label>接管代理端口<input type="number" min="0" max="65535" required disabled={locked||busy} value={data.ports.proxy_port} onChange={e=>setData({...data,ports:{...data.ports,proxy_port:Number(e.target.value)}})}/></label><label>管理服务端口<input type="number" min="0" max="65535" required disabled={locked||busy} value={data.ports.service_port} onChange={e=>setData({...data,ports:{...data.ports,service_port:Number(e.target.value)}})}/></label></div><div className="form-footer"><span>当前管理 {data.actual_service_port??"未运行"} · 当前接管 {data.actual_proxy_port??"未运行"}</span><button disabled={locked||busy}>保存端口</button></div></form></section></>}</>;
}
